### ISSUE TITLE
withAuth Guard

### ISSUE THREAD

**Issue by CHAUDHARYS1** [CHAUDHARYS1/take-my-recipe#34]
**Is your feature request related to a problem? Please describe.**
Users get error when they go to a certain route but are not logged in. Instead of 404 error, users should be redirected to the appropriate page.

**Describe the solution you'd like**
Protect Routes with Middleware so that users who are not logged in are redirected to the appropriate page.

**Comment by jaya1983** [comment]
This is already in place, issue can be closed
